# Generated by Django 4.2 on 2025-03-25 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nouritureGrammes', models.IntegerField()),
                ('cages', models.IntegerField()),
                ('argentCents', models.IntegerField()),
                ('ageMois', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(max_length=1)),
                ('moisNaissance', models.IntegerField()),
                ('moisGravide', models.IntegerField(null=True)),
                ('elevage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.elevage')),
            ],
        ),
    ]
