# Generated by Django 4.2 on 2025-03-26 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='nom',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individu',
            name='elevage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lapins', to='app.elevage'),
        ),
    ]
