# Generated by Django 4.2 on 2025-03-31 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_individu_moisdécès'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageMois', models.IntegerField()),
                ('texte', models.CharField(max_length=200)),
                ('elevage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='app.elevage')),
                ('individu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='app.individu')),
            ],
        ),
    ]
