class Config():
    PRIX_GRAMME_NOURITURE_CENTS = 0.1
    PRIX_VENTE_LAPIN_CENTS = 1000
    PRIX_CAGE_CENTS = 100
    CONSOMMATION_NOURITURE_GRAMMES_2_MOIS = 100
    CONSOMMATION_NOURITURE_GRAMMES_3_MOIS = 250
    MAX_LAPEREAUX_PAR_PORTEE = 3
    MAX_LAPINS_PAR_CAGES = 6
    MIN_AGE_MOIS_GRAVIDE = 6
    MAX_AGE_MOIS_GRAVIDE = 12 * 4
    DUREE_GRAVIDITE_MOIS = 2
