NOM_LAPINS = [
    "Mochi", "Peanut", "Pudding", "Biscuit", "Honey",
    "Cinnamon", "Marshmallow", "Jellybean", "Cupcake", "Waffles",
    "Clover", "Daisy", "Willow", "Pebbles", "Sunny",
    "Blossom", "Thistle", "Berry", "Hazel", "Dandelion",
    "Pippin", "Nibbles", "Whiskers", "Puffy", "Snickers",
    "Button", "Pogo", "Tumble", "Wiggles", "Binky",
    "Oliver", "Bella", "Charlie", "Lily", "Milo",
    "Sophie", "Archie", "Rosie", "Toby", "Luna",
    "Boop", "Zoom", "Flopsy", "Bounce", "Wiggly",
    "Snoof", "Doodle", "Zippy", "Twitch", "Noodle",
    "Thumper", "Lola", "Bugs", "Judy", "Roger",
    "Snowball", "Peter", "Miffy", "Bunnicula", "Fiver",
    "Pearl", "Duchess", "Bentley", "Celeste", "Winston",
    "Violet", "Theodore", "Penelope", "Sebastian", "Arabella",
    "Cotton", "Fluffy", "Cloud", "Puff", "Snowball",
    "Fuzzy", "Whisp", "Velvet", "Cashmere", "Silky",
    "Sprout", "Doodlebug", "Pippa", "Twix", "Niblet",
    "Gizmo", "Tofu", "Ziggy", "Pippy", "Squish",
    "Pebble", "Sunny", "Pip", "Tilly", "Remy",
    "Scout", "Tansy", "Comet", "Roo", "Pippet"
]
